spring:
  application:
    name: ArcadiaLogin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://35.216.99.76:3306/test
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver


  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 3rVboUvxEZ7HwQuY30OB
            client-secret: 4vVsarkBmq
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: fbe01848499bbc280e8f47c457cf03a3
            client-secret: oZT4PQHd5HKHVVAwNm9pTe7G7w4pZjgH
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
    refresh-token-expiration-time: 604800000
    refresh-expiration-time: 604800000

logging:
  level:
    profit.login.jwt: DEBUG



server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true